apiVersion: v1
kind: Service
metadata:
  name: s8-sensor
  namespace: kube-prometheus-stack
  labels:
    app: s8-sensor
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9105
      targetPort: 9105
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: s8-sensor
  namespace: kube-prometheus-stack
  labels:
    app: s8-sensor
subsets:
  - addresses:
      - ip: ${Raspberry Pi IP}
    ports:
      - name: metrics
        port: 9105
        protocol: TCP